name: check

on: [push]

jobs:

  install:
    runs-on: ubuntu-latest
    name: Testing GitHub action
    steps:
      - uses: actions/checkout@v2
      - name: install-clay
        uses: ./
      - name: which cplay
        run: which cplay
      - name: cplay --version
        run: cplay --version

