name: check

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Testing GitHub action
    steps:
      - uses: actions/checkout@v2
      - name: install-clay
        uses: ./
        with:
          ci: false
      - name: which cplay
        run: which cplay
      - name: cplay --version
        run: cplay --version

  install_one:
    runs-on: ubuntu-latest
    name: "Install a single module"
    steps:
      - uses: actions/checkout@v2
      - name: install-with-cplay A1z-Html
        uses: ./
        with:
          install: "A1z-Html"
          ci: false

  install_notests:
    runs-on: ubuntu-latest
    name: "Install without tests and args"
    steps:
      - uses: actions/checkout@v2
      - name: install-with-cplay A1z-Html
        uses: ./
        with:
          install: "A1z-Html"
          tests: false
          args: "--reinstall --installdir vendor"
          ci: false

  install_two:
    runs-on: ubuntu-latest
    name: "Install two modules"
    steps:
      - uses: actions/checkout@v2
      - name: install-with-cplay abbreviation A1z-Html
        uses: ./
        with:
          install: |
            abbreviation
            ACH
          ci: false

  install_cpanfile:
    runs-on: ubuntu-latest
    name: "Install using a cpanfile"
    steps:
      # for now install missing dependencies using cpm [can be removed once indexed]
      - uses: perl-actions/install-cpm@v1.1
        with:
          install: "Module::CPANfile"
      # ......
      - uses: actions/checkout@v2
      - name: "Create a cpanfile"
        run: |
          echo "requires 'A1z-Html';" >> cpanfile
      - name: install-with-cplay cpanfile
        uses: ./
        with:
          cpanfile: "cpanfile"
          ci: false

  install_from_tarball:
    runs-on: ubuntu-latest
    name: "Install from tarball"
    steps:
      - uses: actions/checkout@v2
      - name: "install-with-cplay --from-tarball"
        uses: ./
        with:
          tarball: "https://github.com/pause-play/A1z-Html/archive/p5.tar.gz"
          ci: false
